"""
simple Python interface to the live Multi-Radar/Multi-Sensor (MRMS) server.


Examples:
---------

```python
import matplotlib.pyplot as plt
import cartopy.crs as ccrs
import mrms

fig, ax = plt.subplots(subplot_kw={'projection': ccrs.PlateCarree()})
ax.coastlines()

arr = mrms.get(mrms.MERGED_BASE_REFLECTIVITY_QC)
arr[arr < 0] = float('nan')

ax.pcolormesh(mrms.longitude, mrms.latitude, arr, transform=ccrs.PlateCarree())
```
"""

__all__ = ["file_directory", "get", "load", "Vars", "latitude", "longitude", "Array", "MRMS2dVariable"]
import typing as __T

from .core import Array, file_directory, get, latitude, load, longitude

# -------------------------------------------------------------------------------------------------
# Define the type of the variables in the MRMS dataset.
# -------------------------------------------------------------------------------------------------
MRMS2dVariable = __T.Literal[
    "BREF_1HR_MAX",
    "BrightBandBottomHeight",
    "BrightBandTopHeight",
    "CREF_1HR_MAX",
    "EchoTop_18",
    "EchoTop_30",
    "EchoTop_50",
    "EchoTop_60",
    "FLASH",
    "GaugeInflIndex_01H_Pass1",
    "GaugeInflIndex_01H_Pass2",
    "GaugeInflIndex_03H_Pass1",
    "GaugeInflIndex_03H_Pass2",
    "GaugeInflIndex_06H_Pass1",
    "GaugeInflIndex_06H_Pass2",
    "GaugeInflIndex_12H_Pass1",
    "GaugeInflIndex_12H_Pass2",
    "GaugeInflIndex_24H_Pass1",
    "GaugeInflIndex_24H_Pass2",
    "GaugeInflIndex_48H_Pass1",
    "GaugeInflIndex_48H_Pass2",
    "GaugeInflIndex_72H_Pass1",
    "GaugeInflIndex_72H_Pass2",
    "H50_Above_-20C",
    "H50_Above_0C",
    "H60_Above_-20C",
    "H60_Above_0C",
    "HeightCompositeReflectivity",
    "HeightLowLevelCompositeReflectivity",
    "LVL3_HREET",
    "LVL3_HighResVIL",
    "LayerCompositeReflectivity_ANC",
    "LayerCompositeReflectivity_High",
    "LayerCompositeReflectivity_Low",
    "LayerCompositeReflectivity_Super",
    "LowLevelCompositeReflectivity",
    "LtgJumpGrid",
    "LtgJumpGrid_Max_005min",
    "MESH",
    "MESH_Max_30min",
    "MESH_Max_60min",
    "MESH_Max_120min",
    "MESH_Max_240min",
    "MESH_Max_360min",
    "MESH_Max_1440min",
    "MergedAzShear_0-2kmAGL",
    "MergedAzShear_3-6kmAGL",
    "MergedBaseReflectivity",
    "MergedBaseReflectivityQC",
    "MergedReflectivityAtLowestAltitude",
    "MergedReflectivityComposite",
    "MergedReflectivityQC",
    "MergedReflectivityQCComposite",
    "MergedRhoHV",
    "MergedZdr",
    "Model_0degC_Height",
    "Model_SurfaceTemp",
    "Model_WetBulbTemp",
    "MultiSensor_QPE_01H_Pass1",
    "MultiSensor_QPE_01H_Pass2",
    "MultiSensor_QPE_03H_Pass1",
    "MultiSensor_QPE_03H_Pass2",
    "MultiSensor_QPE_06H_Pass1",
    "MultiSensor_QPE_06H_Pass2",
    "MultiSensor_QPE_12H_Pass1",
    "MultiSensor_QPE_12H_Pass2",
    "MultiSensor_QPE_24H_Pass1",
    "MultiSensor_QPE_24H_Pass2",
    "MultiSensor_QPE_48H_Pass1",
    "MultiSensor_QPE_48H_Pass2",
    "MultiSensor_QPE_72H_Pass1",
    "MultiSensor_QPE_72H_Pass2",
    "NLDN_CG_001min_AvgDensity",
    "NLDN_CG_005min_AvgDensity",
    "NLDN_CG_015min_AvgDensity",
    "NLDN_CG_030min_AvgDensity",
    "POSH",
    "PrecipFlag",
    "PrecipRate",
    "RadarAccumulationQualityIndex_01H",
    "RadarAccumulationQualityIndex_03H",
    "RadarAccumulationQualityIndex_06H",
    "RadarAccumulationQualityIndex_12H",
    "RadarAccumulationQualityIndex_24H",
    "RadarAccumulationQualityIndex_48H",
    "RadarAccumulationQualityIndex_72H",
    "RadarOnly_QPE_01H",
    "RadarOnly_QPE_03H",
    "RadarOnly_QPE_06H",
    "RadarOnly_QPE_12H",
    "RadarOnly_QPE_15M",
    "RadarOnly_QPE_24H",
    "RadarOnly_QPE_48H",
    "RadarOnly_QPE_72H",
    "RadarOnly_QPE_Since12Z",
    "RadarQualityIndex",
    "ReflectivityAtLowestAltitude",
    "Reflectivity_-5C",
    "Reflectivity_-10C",
    "Reflectivity_-15C",
    "Reflectivity_-20C",
    "Reflectivity_0C",
    "RotationTrack30min",
    "RotationTrack60min",
    "RotationTrack120min",
    "RotationTrack240min",
    "RotationTrack360min",
    "RotationTrack1440min",
    "RotationTrackML30min",
    "RotationTrackML60min",
    "RotationTrackML120min",
    "RotationTrackML240min",
    "RotationTrackML360min",
    "RotationTrackML1440min",
    "SHI",
    "SeamlessHSR",
    "SeamlessHSRHeight",
    "SyntheticPrecipRateID",
    "VII",
    "VIL",
    "VIL_Density",
    "VIL_Max_120min",
    "VIL_Max_1440min",
    "WarmRainProbability",
]
Vars = MRMS2dVariable
__args: tuple[MRMS2dVariable, ...] = __T.get_args(MRMS2dVariable)
(
    BREF_1HR_MAX,
    BRIGHT_BAND_BOTTOM_HEIGHT,
    BRIGHT_BAND_TOP_HEIGHT,
    CREF_1HR_MAX,
    ECHO_TOP_18,
    ECHO_TOP_30,
    ECHO_TOP_50,
    ECHO_TOP_60,
    FLASH,
    GAUGE_INFL_INDEX_01_H_PASS1,
    GAUGE_INFL_INDEX_01_H_PASS2,
    GAUGE_INFL_INDEX_03_H_PASS1,
    GAUGE_INFL_INDEX_03_H_PASS2,
    GAUGE_INFL_INDEX_06_H_PASS1,
    GAUGE_INFL_INDEX_06_H_PASS2,
    GAUGE_INFL_INDEX_12_H_PASS1,
    GAUGE_INFL_INDEX_12_H_PASS2,
    GAUGE_INFL_INDEX_24_H_PASS1,
    GAUGE_INFL_INDEX_24_H_PASS2,
    GAUGE_INFL_INDEX_48_H_PASS1,
    GAUGE_INFL_INDEX_48_H_PASS2,
    GAUGE_INFL_INDEX_72_H_PASS1,
    GAUGE_INFL_INDEX_72_H_PASS2,
    H50_ABOVE_20C,
    H50_ABOVE_0C,
    H60_ABOVE_20C,
    H60_ABOVE_0C,
    HEIGHT_COMPOSITE_REFLECTIVITY,
    HEIGHT_LOW_LEVEL_COMPOSITE_REFLECTIVITY,
    LVL3_HR_EET,
    LVL3_HIGH_RES_VIL,
    LAYER_COMPOSITE_REFLECTIVITY_ANC,
    LAYER_COMPOSITE_REFLECTIVITY_HIGH,
    LAYER_COMPOSITE_REFLECTIVITY_LOW,
    LAYER_COMPOSITE_REFLECTIVITY_SUPER,
    LOW_LEVEL_COMPOSITE_REFLECTIVITY,
    LTG_JUMP_GRID,
    LTG_JUMP_GRID_MAX_5MIN,
    MESH,
    MESH_MAX_30MIN,
    MESH_MAX_60MIN,
    MESH_MAX_120MIN,
    MESH_MAX_240MIN,
    MESH_MAX_360MIN,
    MESH_MAX_1440MIN,
    MERGED_AZ_SHEAR_0_2KM_AGL,
    MERGED_AZ_SHEAR_3_6KM_AGL,
    MERGED_BASE_REFLECTIVITY,
    MERGED_BASE_REFLECTIVITY_QC,
    MERGED_REFLECTIVITY_AT_LOWEST_ALTITUDE,
    MERGED_REFLECTIVITY_COMPOSITE,
    MERGED_REFLECTIVITY_QC,
    MERGED_REFLECTIVITY_QC_COMPOSITE,
    MERGED_RHO_H_V,
    MERGED_ZDR,
    MODEL_0C_HEIGHT,
    MODEL_SURFACE_TEMP,
    MODEL_WET_BULB_TEMP,
    MULTI_SENSOR_QPE_01H_PASS1,
    MULTI_SENSOR_QPE_01H_PASS2,
    MULTI_SENSOR_QPE_03H_PASS1,
    MULTI_SENSOR_QPE_03H_PASS2,
    MULTI_SENSOR_QPE_06H_PASS1,
    MULTI_SENSOR_QPE_06H_PASS2,
    MULTI_SENSOR_QPE_12H_PASS1,
    MULTI_SENSOR_QPE_12H_PASS2,
    MULTI_SENSOR_QPE_24H_PASS1,
    MULTI_SENSOR_QPE_24H_PASS2,
    MULTI_SENSOR_QPE_48H_PASS1,
    MULTI_SENSOR_QPE_48H_PASS2,
    MULTI_SENSOR_QPE_72H_PASS1,
    MULTI_SENSOR_QPE_72H_PASS2,
    NLDN_CG_001_MIN_AVG_DENSITY,
    NLDN_CG_005_MIN_AVG_DENSITY,
    NLDN_CG_015_MIN_AVG_DENSITY,
    NLDN_CG_030_MIN_AVG_DENSITY,
    POSH,
    PRECIP_FLAG,
    PRECIP_RATE,
    RADAR_ACCUMULATION_QUALITY_INDEX_01H,
    RADAR_ACCUMULATION_QUALITY_INDEX_03H,
    RADAR_ACCUMULATION_QUALITY_INDEX_06H,
    RADAR_ACCUMULATION_QUALITY_INDEX_12H,
    RADAR_ACCUMULATION_QUALITY_INDEX_24H,
    RADAR_ACCUMULATION_QUALITY_INDEX_48H,
    RADAR_ACCUMULATION_QUALITY_INDEX_72H,
    RADAR_ONLY_QPE_01H,
    RADAR_ONLY_QPE_03H,
    RADAR_ONLY_QPE_06H,
    RADAR_ONLY_QPE_12H,
    RADAR_ONLY_QPE_15M,
    RADAR_ONLY_QPE_24H,
    RADAR_ONLY_QPE_48H,
    RADAR_ONLY_QPE_72H,
    RADAR_ONLY_QPE_SINCE_12Z,
    RADAR_QUALITY_INDEX,
    REFLECTIVITY_AT_LOWEST_ALTITUDE,
    REFLECTIVITY_M05C,
    REFLECTIVITY_M10C,
    REFLECTIVITY_M15C,
    REFLECTIVITY_M20C,
    REFLECTIVITY_M00C,
    ROTATION_TRACK_30MIN,
    ROTATION_TRACK_60MIN,
    ROTATION_TRACK_120MIN,
    ROTATION_TRACK_240MIN,
    ROTATION_TRACK_360MIN,
    ROTATION_TRACK_1440MIN,
    ROTATION_TRACK_ML_30MIN,
    ROTATION_TRACK_ML_60MIN,
    ROTATION_TRACK_ML_120MIN,
    ROTATION_TRACK_ML_240MIN,
    ROTATION_TRACK_ML_360MIN,
    ROTATION_TRACK_ML_1440MIN,
    SHI,
    SEAMLESS_HSR,
    SEAMLESS_HSR_HEIGHT,
    SYNTHETIC_PRECIP_RATE_ID,
    VII,
    VIL,
    VIL_DENSITY,
    VIL_MAX_120MIN,
    VIL_MAX_1440MIN,
    WARM_RAIN_PROBABILITY,
) = __args
del __args, __T
